#!/usr/bin/env bash
# Overlay custom Android files on top of the default Flutter scaffold
# generated by `flutter create`.
#
# Run AFTER: flutter create --platforms=android --org com.jessicacarter --project-name chocoblock .
# Run BEFORE: flutter build apk

set -euo pipefail
cd "$(dirname "$0")/.."

SETUP_DIR="setup/android"
ANDROID_APP="android/app"
ANDROID_RES="$ANDROID_APP/src/main/res"

echo "Overriding Android files from $SETUP_DIR ..."

# 1. AndroidManifest.xml (portrait lock, hardware accel, no cleartext)
cp "$SETUP_DIR/AndroidManifest.xml" "$ANDROID_APP/src/main/AndroidManifest.xml"

# 2. Styles + launch background
cp "$SETUP_DIR/styles.xml" "$ANDROID_RES/values/styles.xml"
mkdir -p "$ANDROID_RES/drawable"
cp "$SETUP_DIR/launch_background.xml" "$ANDROID_RES/drawable/launch_background.xml"

# 3. Launcher icons at all 5 densities
for density in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
  cp "$SETUP_DIR/mipmap-$density/ic_launcher.png"     "$ANDROID_RES/mipmap-$density/ic_launcher.png"
  cp "$SETUP_DIR/mipmap-$density/ic_launcher_round.png" "$ANDROID_RES/mipmap-$density/ic_launcher_round.png"
done

# 4. proguard rules (for release builds with minify)
cp "$SETUP_DIR/proguard-rules.pro" "$ANDROID_APP/proguard-rules.pro"

# 5. Patch android/app/build.gradle.kts: set minSdk = 21 (webview_flutter requires 21+,
#    but our Flame-only app could go lower; keep 21 for audio plugin compat).
#    Also enable release-signed-with-debug for now (replace before Play Store).
BUILD_GRADLE="$ANDROID_APP/build.gradle.kts"
if grep -q "minSdk = flutter.minSdkVersion" "$BUILD_GRADLE"; then
  sed -i 's|minSdk = flutter.minSdkVersion|minSdk = 21|' "$BUILD_GRADLE"
  echo "  patched minSdk = 21 in $BUILD_GRADLE"
fi

# Add release signing config (use debug key for now so release APK installs without keystore).
if ! grep -q "signingConfig = signingConfigs.getByName(\"debug\")" "$BUILD_GRADLE"; then
  # Insert signingConfig line into the release build type block.
  python3 - <<'PYEOF'
import re, pathlib
p = pathlib.Path("android/app/build.gradle.kts")
src = p.read_text()
# Find the "release { ... }" block and inject signingConfig at the top of it.
new = re.sub(
    r'(release\s*\{)',
    r'\1\n            signingConfig = signingConfigs.getByName("debug")',
    src,
    count=1,
)
# Also enable minify + proguard for release
new = re.sub(
    r'(release\s*\{[^}]*?)isMinifyEnabled\s*=\s*(?:true|false)',
    r'\1isMinifyEnabled = true',
    new,
    count=1,
)
# Add proguard files reference to release
if 'proguardFiles(' not in new:
    new = re.sub(
        r'(release\s*\{[^}]*?isMinifyEnabled = true)',
        r'\1\n            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")',
        new,
        count=1,
    )
p.write_text(new)
PYEOF
  echo "  patched release signing + minify in $BUILD_GRADLE"
fi

echo "Done. Android overlay applied."
